import pandas as pd, numpy as np, joblib, json, os

print('='*55)
print('STEP 3 — DATA QUALITY VALIDATION')
print('='*55)
df = pd.read_csv('data/processed/master_dataset.csv')
pred_df = pd.read_csv('data/predictions/india_predictions.csv')
print(f'Master dataset rows  : {len(df)}')
print(f'Prediction CSV rows  : {len(pred_df)}')
with open('data/predictions/india_predictions.json') as f:
    jdata = json.load(f)
print(f'Prediction JSON recs : {len(jdata)}')
print(f'Unique states/UTs    : {df["state"].nunique()}')
print(f'Duplicate pairs      : {df.duplicated(["district","state"]).sum()}')
print(f'Missing values       : {df.isnull().sum().sum()}')
bad_lat = ((df.latitude < 5) | (df.latitude > 40)).sum()
bad_lon = ((df.longitude < 65) | (df.longitude > 100)).sum()
print(f'Invalid lat (<5/>40) : {bad_lat}')
print(f'Invalid lon (<65/>100): {bad_lon}')
print()
print('Flood risk dist:', df.flood_risk.value_counts().to_dict())
print('LS risk dist   :', df.landslide_risk.value_counts().to_dict())
print()
print('Env feature ranges:')
for c in ['rainfall','river_level','soil_moisture','slope','elevation']:
    print(f'  {c:20}: {df[c].min():.2f} - {df[c].max():.2f}')
print()
print('[!] DATA TYPE: SYNTHETIC/DEMO ONLY — not real sensor data.')
print()
print('='*55)
print('STEP 4 — MODEL ARTIFACT VERIFICATION')
print('='*55)
for mname, mpath in [('flood','models/flood_model.pkl'),('landslide','models/landslide_model.pkl')]:
    bundle = joblib.load(mpath)
    print(f'{mname} model keys: {list(bundle.keys())}')
    meta_path = mpath.replace('.pkl','_metadata.json')
    with open(meta_path) as f:
        meta = json.load(f)
    acc = meta.get('synthetic_validation_accuracy','N/A')
    print(f'  Synthetic val accuracy : {acc}')
    print(f'  Features               : {bundle["features"]}')
    print(f'  Target                 : {bundle["target"]}')
    print()
print('[OK] All model artifacts verified.')
